# Site settings
url             : 'https://ahmetcadirci.com.tr'
baseurl         : '/'
disqus_shortname: 'ahmet25'


# Seo settings
title      : 'Ahmet Çadırcı'
description: 'Ahmet Çadırcı kişisel web sitemde blog yazıları, video, podcast vb. içerikler yer almaktadır. İletişim sayfasından bana ulaşabilirsiniz.'
author     : 'ahmetcadircicom'
lang       : 'tr-TR'
twitter:
  username: 'ahmetcadircicom'
  card    : summary
  creator : 'ahmetcadircicom'

facebook:
  app_id   : 
  publisher: 
  admins   : 

logo: '/images/favicons/apple-touch-icon-180x180.png'

social:
  name: Ahmet Çadırcı
  links:
    - https://github.com/ahmetcadirci25

author:
  name               : 'Ahmet Çadırcı'
  email              : ahmetcadirci25@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate   : 5
permalink  : /:year/:title/
markdown   : kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-include-cache

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.jekyll-cache']